baseURL = 'https://example.org/'
languageCode = 'zh'
title = '优秀传统文化'
theme = 'ananke'
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
publishDir ="docs"
