baseURL = 'https://babibanibanidsx.github.io/-/'
languageCode = 'zh'
canonifyurls = true
title = '优秀传统文化'
theme = 'ananke'
publishDir = "docs"
[markup]
defaultMarkdownHandler = "goldmark"
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

